// <auto-generated />
namespace vNext.SM.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTable3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTable3));
        
        string IMigrationMetadata.Id
        {
            get { return "201702020130105_AddTable3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
